reviews:
  # Minimize walkthrough visibility
  collapse_walkthrough: true
  sequence_diagrams: false
  profile: "chill"
  request_changes_workflow: true

  path_filters:
    - "!**/.cursor/**"
    - "!**/.claude/**"
    - "!**/.bmad-core/**"
    - "!**/bmad-core/**"
