reviews:
  # Minimize walkthrough visibility
  collapse_walkthrough: true
  sequence_diagrams: false
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: false

  path_filters:
    # Include only these specific paths
    - "services/**"
    - "tests/**"
    - "docker-compose.yaml"
    - "docker-compose.test.yaml"
    - "Makefile"
    - ".github/**"
    # Exclude these paths for extra clarity
    - "!**/.cursor/**"
    - "!.claude/**"
    - "!**/.claude/**"
    - "!**/.bmad-core/**"
    - "!docs/**"
    - "!**/docs/**"
