# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
        exclude: 'tests/e2e/testdata/flows/error-cases/invalid-json\.json|cmd/commands/\.flows/flows/corrupted-flow\.json'
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/mpalmer/action-validator
    rev: v0.7.1
    hooks:
    - id: action-validator

  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        entry: golangci-lint run --fix
        language: system
        always_run: true
        pass_filenames: false

      - id: go-mod-tidy
        name: go mod tidy
        entry: go mod tidy
        language: system
        types: [go]
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: gofumpt -l -w
        language: system
        types: [go]
        pass_filenames: true

      - id: go-imports
        name: go imports
        entry: goimports -local github.com/boarlabsxyz/mono-expenses -w
        language: system
        types: [go]
        pass_filenames: true

      - id: go-test-unit
        name: go test-unit
        entry: make test-unit
        language: system
        types: [go]
        pass_filenames: false

      - id: go-test-e2e
        name: go test-e2e
        entry: make test-e2e
        language: system
        types: [go]
        pass_filenames: false

      - id: no-nolint-comments
        name: Ensure no //nolint comments
        entry: bash -c
        args:
          - 'count=$(grep -o "//nolint:" $(find . -name "*.go" -not -path "./.git/*" -not -path "./coverage/*" -not -path "./bin/*") 2>/dev/null | wc -l || echo 0); if [ "$count" -gt 0 ]; then echo "Found $count //nolint: comments in Go files. Policy requires zero //nolint: comments."; grep -r "//nolint:" . --exclude-dir=.git --exclude-dir=coverage --exclude-dir=bin --include="*.go" 2>/dev/null || true; exit 1; fi'
        language: system
        files: '\.go$'
        pass_filenames: false
