version: '3.8'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    container_name: mcp-backend-test
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - test-network

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: mcp-frontend-test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8080
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:3000"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - test-network

  playwright-test:
    build:
      context: ./tests
      dockerfile: Dockerfile.test
    container_name: mcp-playwright-test
    environment:
      - CI=true
      - PLAYWRIGHT_BASE_URL=http://frontend:3000
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - test-network
    volumes:
      - ./test-results:/app/test-results
      - ./playwright-report:/app/playwright-report

networks:
  test-network:
    driver: bridge
    name: mcp-test-network
