version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: standard
  enable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    # - containedctx  # TODO: Fix context.Context in struct fields
    # - contextcheck  # TODO: Fix non-inherited context usage
    - copyloopvar
    - cyclop
    - decorder
    # - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    # - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    # - funcorder  # TODO: Fix function ordering (declarations before usage)
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange

    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    # - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    # - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl_v5
    - zerologlint
  # Disable specific linters.
  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 80
      statements: 40
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
    forbidigo:
      forbid:
        - pattern: '^fmt\.(Print(f|ln)?|Errorf)$'
          msg: 'use slog for logging and proper error wrapping'
    tagliatelle:
      # For internal domain models and application code
      case:
        rules:
          json: snake  # Internal JSON APIs use snake_case
          yaml: snake  # All YAML configs use snake_case
          # Note: GitHub API structures (in adapters/github and models/thread.go)
          # are excluded below to match GitHub's camelCase API contract

  exclusions:
    generated: lax
    warn-unused: true
    rules:
      # GitHub API structures must use camelCase to match GitHub's API contract
      - path: internal/adapters/github/.*\.go
        linters:
          - tagliatelle
      - path: internal/domain/models/thread\.go
        linters:
          - tagliatelle
      # claudecode is third-party code - exclude from err113 and wrapcheck
      - path: claudecode/.*\.go
        linters:
          - err113
          - wrapcheck
      # Custom error package defines errors - exclude from err113
      - path: internal/pkg/errors/errors\.go
        linters:
          - err113
      # Our custom error constructors are already wrapped - exclude from wrapcheck
      - path: .*\.go
        text: "error returned from external package is unwrapped.*bmad-cli/internal/pkg/errors"
        linters:
          - wrapcheck
      # Test files can use dynamic errors for testing
      - path: .*_test\.go
        linters:
          - err113
      # Git handlers use descriptive dynamic errors for user-facing messages
      - path: internal/infrastructure/git/handlers/.*\.go
        linters:
          - err113
      # Story loader validation uses descriptive dynamic errors
      - path: internal/infrastructure/story/story_loader\.go
        linters:
          - err113
      # Yamale validator wraps external tool errors
      - path: internal/infrastructure/validation/yamale_validator\.go
        linters:
          - err113
      # Test scenario parsing uses dynamic errors
      - path: internal/domain/models/story/test_scenario\.go
        linters:
          - err113
      # Interface method errors don't need wrapping within our codebase
      - path: .*\.go
        text: "error returned from interface method should be wrapped"
        linters:
          - wrapcheck
      # Shell command runner errors are wrapped at higher levels
      - path: .*\.go
        text: "error returned from external package is unwrapped.*CommandRunner.*Run"
        linters:
          - wrapcheck
      # Context errors are standard library and don't need wrapping
      - path: .*\.go
        text: "error returned from interface method should be wrapped.*context.Context.*Err"
        linters:
          - wrapcheck
      # os/exec.LookPath errors can be returned directly
      - path: .*\.go
        text: "error returned from external package is unwrapped.*os/exec.LookPath"
        linters:
          - wrapcheck
      # AIGenerator is internal package - errors already wrapped
      - path: .*\.go
        text: "error returned from external package is unwrapped.*AIGenerator.*Generate"
        linters:
          - wrapcheck
      # ThreadProcessor is internal package - errors already wrapped
      - path: .*\.go
        text: "error returned from external package is unwrapped.*ThreadProcessor.*AnalyzeThread"
        linters:
          - wrapcheck
      # Command Execute methods - errors already wrapped at source
      - path: cmd/.*\.go
        text: "error returned from external package is unwrapped.*Command.*Execute"
        linters:
          - wrapcheck
