# Test Requirements Registry (Flattened Structure)
# This file tracks all test scenarios and their implementation status across the codebase
metadata:
  title: "Test Requirements Registry"
  version: "2.0"
  last_updated: "2025-10-08"
  description: "Flattened scenario registry tracking implementation status and user story lineage"

# Flattened scenario registry
# Each scenario is tracked independently with:
# - Implementation status (pending/implemented/failed/outdated)
# - File path for test implementation
# - User story lineage (tracks which stories modified this scenario)
# - Merged steps from all contributing stories
scenarios:
  INT-001:
    description: "server responds with correct status"
    category: "backend"
    requirement: "Backend /version endpoint returns 1.0.0"
    level: "integration"
    priority: "P0"
    acceptance_criteria: ["AC-1"]
    implementation_status:
      status: "pending"
      file_path: "tests/integration/backend.test.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-001"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "Fiber server is running with version endpoint"
      when:
        - "HTTP GET request is made to /version"
      then:
        - "server responds with correct JSON and 200 status"

  E2E-001:
    description: "service returns version with headers"
    category: "backend"
    requirement: "Backend /version endpoint returns 1.0.0"
    level: "e2e"
    priority: "P0"
    acceptance_criteria: ["AC-1"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-001"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "full backend service is deployed and running"
      when:
        - "external HTTP client calls /version endpoint"
      then:
        - "service responds with \"1.0.0\" and proper HTTP headers"

  E2E-002:
    description: "health endpoint accessible via HTTP"
    category: "backend"
    requirement: "Backend /health endpoint returns healthy status"
    level: "e2e"
    priority: "P0"
    acceptance_criteria: ["AC-2"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-006"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "services are running with health endpoints"
      when:
        - "health check URLs are accessed via HTTP"
      then:
        - "both services respond with healthy status"

  E2E-003:
    description: "returns 404 for non-existent endpoints"
    category: "backend"
    requirement: "Backend handles 404 for non-existent endpoints"
    level: "e2e"
    priority: "P1"
    acceptance_criteria: ["AC-3"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-004"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service is running"
      when:
        - "GET request is sent to non-existent endpoint"
      then:
        - "service returns 404 status code"
        - and: "response indicates endpoint was not found"

  E2E-004:
    description: "returns 405 for POST on version endpoint"
    category: "backend"
    requirement: "Backend rejects invalid HTTP methods"
    level: "e2e"
    priority: "P1"
    acceptance_criteria: ["AC-4"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-005"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service is running"
      when:
        - "POST request is sent to /version endpoint"
      then:
        - "service returns 405 Method Not Allowed status code"
        - and: "response indicates method is not allowed"

  E2E-005:
    description: "includes CORS headers for frontend requests"
    category: "backend"
    requirement: "Backend provides CORS headers for frontend"
    level: "e2e"
    priority: "P1"
    acceptance_criteria: ["AC-5"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-007"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service is running"
      when:
        - "request with Origin header from frontend domain is sent"
      then:
        - "response includes appropriate CORS headers"
        - and: "Access-Control-Allow-Origin header allows frontend domain"

  INT-002:
    description: "Next.js routes serve pages correctly"
    category: "frontend"
    requirement: "Frontend single-page application loads successfully"
    level: "integration"
    priority: "P0"
    acceptance_criteria: ["AC-6"]
    implementation_status:
      status: "pending"
      file_path: "tests/integration/frontend.test.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-002"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "Next.js App Router is configured"
      when:
        - "application routes are accessed"
      then:
        - "pages are served correctly by Next.js framework"

  E2E-006:
    description: "SPA loads in browser"
    category: "frontend"
    requirement: "Frontend single-page application loads successfully"
    level: "e2e"
    priority: "P0"
    acceptance_criteria: ["AC-6"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-002"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application is built and served"
      when:
        - "browser navigates to application URL"
      then:
        - "single-page application loads and renders in browser"

  INT-003:
    description: "frontend fetches from backend successfully"
    category: "frontend"
    requirement: "Homepage displays backend version at bottom"
    level: "integration"
    priority: "P0"
    acceptance_criteria: ["AC-7"]
    implementation_status:
      status: "pending"
      file_path: "tests/integration/fullstack.test.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-003"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend and backend services are running"
      when:
        - "frontend makes API call to backend version endpoint"
      then:
        - "version \"1.0.0\" is successfully retrieved and displayed"

  E2E-007:
    description: "version appears at bottom of page"
    category: "frontend"
    requirement: "Homepage displays backend version at bottom"
    level: "e2e"
    priority: "P0"
    acceptance_criteria: ["AC-7"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-003"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "full stack application is running"
      when:
        - "user loads homepage in browser"
      then:
        - "backend version \"1.0.0\" appears at bottom of page"

  E2E-008:
    description: "welcome card is visible"
    category: "frontend"
    requirement: "Homepage displays welcome card with features"
    level: "e2e"
    priority: "P1"
    acceptance_criteria: ["AC-8"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-008"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application is loaded"
      when:
        - "user views homepage"
      then:
        - "welcome card is visible"
        - and: "welcome card displays key features"

  E2E-009:
    description: "adapts to different viewport sizes"
    category: "frontend"
    requirement: "Homepage has responsive design"
    level: "e2e"
    priority: "P1"
    acceptance_criteria: ["AC-9"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-010"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application is loaded"
      when:
        - "browser is resized to different viewport sizes"
      then:
        - "homepage layout adapts responsively"
        - and: "all elements remain accessible and properly positioned"

  E2E-010:
    description: "page loads under 2000ms"
    category: "performance"
    requirement: "Homepage loads within 2 seconds"
    level: "e2e"
    priority: "P0"
    acceptance_criteria: ["AC-10"]
    implementation_status:
      status: "pending"
      file_path: "tests/e2e/performance.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-009"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application is deployed"
      when:
        - "user navigates to homepage"
      then:
        - "page fully loads in under 2000ms"
        - and: "all critical resources are loaded within time limit"
