# Test Requirements Registry (Flattened Structure)
# This file tracks all test scenarios and their implementation status across the codebase
metadata:
  title: "Test Requirements Registry"
  version: "2.0"
  last_updated: "2025-10-08"
  description: "Flattened scenario registry tracking implementation status and user story lineage"

# Flattened scenario registry
# Each scenario is tracked independently with:
# - Implementation status (pending/implemented/failed/outdated)
# - File path for test implementation
# - User story lineage (tracks which stories modified this scenario)
# - Merged steps from all contributing stories
scenarios:
  INT-001:
    description: "server responds with correct status"
    service: "backend"
    requirement: "Backend /version endpoint returns 1.0.0"
    level: "integration"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-INT-001"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "Fiber server runs with version endpoint configured"
      when:
        - "client sends HTTP GET request to /version"
      then:
        - "server responds with correct JSON and 200 status"

  INT-002:
    description: "version endpoint rejects invalid methods"
    service: "backend"
    requirement: "Backend rejects invalid HTTP methods"
    level: "integration"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-004"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends POST request to /version endpoint"
      then:
        - "service returns 405 Method Not Allowed status code"
        - and: "response indicates method not allowed"

  INT-003:
    description: "health endpoint returns healthy status"
    service: "backend"
    requirement: "Backend /health endpoint returns healthy status"
    level: "integration"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-002"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "services run with health endpoints configured"
      when:
        - "client accesses health check URLs via HTTP"
      then:
        - "both services respond with healthy status"

  INT-004:
    description: "health endpoint rejects invalid methods"
    service: "backend"
    requirement: "Backend rejects invalid HTTP methods"
    level: "integration"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-004"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends DELETE request to /health endpoint"
      then:
        - "service returns 405 Method Not Allowed status code"
        - and: "response indicates method not allowed"

  INT-005:
    description: "non-existent endpoint returns 404"
    service: "backend"
    requirement: "Backend handles 404 for non-existent endpoints"
    level: "integration"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-003"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends GET request to non-existent endpoint"
      then:
        - "service returns 404 status code"
        - and: "response indicates endpoint does not exist"

  E2E-001:
    description: "service returns version with headers"
    service: "backend"
    requirement: "Backend /version endpoint returns 1.0.0"
    level: "e2e"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-001"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "deployment system deploys full backend service"
      when:
        - "external HTTP client calls /version endpoint"
      then:
        - "service responds with \"1.0.0\" and proper HTTP headers"

  E2E-002:
    description: "health endpoint accessible via HTTP"
    service: "backend"
    requirement: "Backend /health endpoint returns healthy status"
    level: "e2e"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-006"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "services run with health endpoints configured"
      when:
        - "client accesses health check URLs via HTTP"
      then:
        - "both services respond with healthy status"

  E2E-003:
    description: "returns 404 for non-existent endpoints"
    service: "backend"
    requirement: "Backend handles 404 for non-existent endpoints"
    level: "e2e"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-004"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends GET request to non-existent endpoint"
      then:
        - "service returns 404 status code"
        - and: "response indicates endpoint does not exist"

  E2E-004:
    description: "returns 405 for POST on version endpoint"
    service: "backend"
    requirement: "Backend rejects invalid HTTP methods"
    level: "e2e"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-005"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends POST request to /version endpoint"
      then:
        - "service returns 405 Method Not Allowed status code"
        - and: "response indicates method not allowed"

  E2E-005:
    description: "includes CORS headers for frontend requests"
    service: "backend"
    requirement: "Backend provides CORS headers for frontend"
    level: "e2e"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/backend-api.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-007"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "backend service runs"
      when:
        - "client sends request with Origin header from frontend domain"
      then:
        - "server includes appropriate CORS headers in response"
        - and: "Access-Control-Allow-Origin header allows frontend domain"

  INT-006:
    description: "Next.js routes serve pages correctly"
    service: "frontend"
    requirement: "Frontend single-page application loads successfully"
    level: "integration"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/frontend.test.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-002"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "Next.js App Router configures application routes"
      when:
        - "client accesses application routes"
      then:
        - "Next.js framework serves pages correctly"

  E2E-006:
    description: "SPA loads in browser"
    service: "frontend"
    requirement: "Frontend single-page application loads successfully"
    level: "e2e"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-002"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "build system builds and serves frontend application"
      when:
        - "browser navigates to application URL"
      then:
        - "single-page application loads and renders in browser"

  INT-007:
    description: "frontend fetches from backend successfully"
    service: "frontend"
    requirement: "Homepage displays backend version at bottom"
    level: "integration"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/integration/fullstack.test.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-003"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend and backend services run"
      when:
        - "frontend makes API call to backend version endpoint"
      then:
        - "frontend successfully retrieves and displays version \"1.0.0\""

  E2E-007:
    description: "version appears at bottom of page"
    service: "frontend"
    requirement: "Homepage displays backend version at bottom"
    level: "e2e"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-003"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "full stack application runs"
      when:
        - "user loads homepage in browser"
      then:
        - "page displays backend version \"1.0.0\" at bottom"

  E2E-008:
    description: "welcome card is visible"
    service: "frontend"
    requirement: "Homepage displays welcome card with features"
    level: "e2e"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-008"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application loads"
      when:
        - "user views homepage"
      then:
        - "homepage displays welcome card"
        - and: "welcome card displays key features"

  E2E-009:
    description: "adapts to different viewport sizes"
    service: "frontend"
    requirement: "Homepage has responsive design"
    level: "e2e"
    priority: "P1"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/homepage.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-010"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "frontend application loads"
      when:
        - "user resizes browser to different viewport sizes"
      then:
        - "homepage layout adapts responsively"
        - and: "all elements remain accessible and properly positioned"

  E2E-010:
    description: "page loads under 2000ms"
    service: "frontend"
    requirement: "Homepage loads within 2 seconds"
    level: "e2e"
    priority: "P0"
    implementation_status:
      status: "implemented"
      file_path: "tests/e2e/performance.spec.ts"
    last_updated: "2025-10-08"
    user_stories:
      - story_id: "1.1"
        story_file: "docs/stories/1.1-initial-setup.md"
        scenario_id: "1.1-E2E-009"
        merge_date: "2025-09-23"
    merged_steps:
      given:
        - "deployment system deploys frontend application"
      when:
        - "user navigates to homepage"
      then:
        - "page fully loads in under 2000ms"
        - and: "browser loads all critical resources within time limit"
